appId: com.ipmi.gui
productName: IPMI管理工具
directories:
  output: dist

files:
  - "**/*"
  - "!node_modules/.cache/**/*"
  - "!dist/**/*"
  - "!example_servers.json"
  - "!build.bat"
  - "!bin/**"

asar: true

win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  icon: assets/icon.ico
  artifactName: "${productName}-${version}-win-${arch}.${ext}"

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: IPMI管理工具

portable:
  artifactName: "${productName}-${version}-portable.${ext}"
